version: '3.5'

services:

# url format: image://service:container_port zookeeper://zookeeper_singlenode:2181
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka:
    build:
      context: kafka
      dockerfile: kafka.Dockerfile
    hostname: kafka
    ports:
      - 9092:9092
    expose:
      - 9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

#  topic_manager:
#    build:
#      context: topic_manager
#      dockerfile: topic_manager.Dockerfile
#    hostname: topic_manager
#    depends_on:
#      - kafka

  producer:
    build:
      context: producer
      dockerfile: producer.Dockerfile
    hostname: producer
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M

  consumer:
    build:
      context: consumer
      dockerfile: consumer.Dockerfile
      args:
        SPARK_HOME: ${SPARK_HOME}
    hostname: consumer
    depends_on:
      - producer
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M
